services:
  postgres-db:
    image: postgres:16-alpine
    container_name: restaurant_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: restaurant_admin
      POSTGRES_PASSWORD: munich_secure_2026
    volumes:
      - postgres_restaurant_data:/var/lib/postgresql/data

volumes:
  postgres_restaurant_data: