### =========================
### CATEGORIES
### =========================

### Get all categories
GET http://localhost:8080/api/v1/categories

###

### Get category by id
GET http://localhost:8080/api/v1/categories/1

###

### Create category - Pizzas
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Pizzas",
  "description": "Italian pizzas and baked dishes"
}

###

### Create category - Burgers
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Burgers",
  "description": "Big smash burgers with extra bacon"
}

###

### Create category - Salads
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Salads",
  "description": "Fresh salads with chicken, cheese and vegetables"
}

###

### Update category 1
PUT http://localhost:8080/api/v1/categories/1
Content-Type: application/json

{
  "name": "Premium Pizzas",
  "description": "Italian pizzas with premium ingredients"
}

###

### Create invalid category
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "",
  "description": "This request should fail because name is blank"
}

###

### Get category not found
GET http://localhost:8080/api/v1/categories/999

###

### Delete category 3
DELETE http://localhost:8080/api/v1/categories/3

